export default [
  { number: 1, description: 'One Task', playable: true },
  { number: 2, description: 'Two Tasks', playable: true },
  { number: 3, description: 'Mission 3', playable: false },
  { number: 4, description: 'Three Tasks', playable: true },
  { number: 5, description: 'Mission 5', playable: false },
  { number: 6, description: 'Three Tasks, Two Arrows, Dead Zone', playable: true },
  { number: 7, description: 'Mission 7', playable: false },
  { number: 8, description: 'Mission 8', playable: false },
  { number: 9, description: 'Mission 9', playable: false },
  { number: 10, description: 'Four Tasks', playable: true },
  { number: 11, description: 'Mission 11', playable: false },
  { number: 12, description: 'Mission 12', playable: false },
  { number: 13, description: 'Mission 13', playable: false },
  { number: 14, description: 'Four Tasks, Three Arrows, Dead Zone', playable: true },
  { number: 15, description: 'Mission 15', playable: false },
  { number: 16, description: 'Mission 16', playable: false },
  { number: 17, description: 'Mission 17', playable: false },
  { number: 18, description: 'Five Tasks, Disruption 2', playable: true },
  { number: 19, description: 'Five Tasks, 1, Disruption 3', playable: true },
  { number: 20, description: 'Mission 20', playable: false },
  { number: 21, description: 'Five Tasks, 1 2, Dead Zone', playable: true },
  { number: 22, description: 'Mission 22', playable: false },
  { number: 23, description: 'Mission 23', playable: false },
  { number: 24, description: 'Mission 24', playable: false },
  { number: 25, description: 'Six Tasks, two arrows, dead zone', playable: true },
  { number: 26, description: 'Mission 26', playable: false },
  { number: 27, description: 'Mission 27', playable: false },
  { number: 28, description: 'Six Tasks, 1 lambda, Disruption 3', playable: true },
  { number: 29, description: 'Mission 29', playable: false },
  { number: 30, description: 'Six Tasks, three arrows, Disruption 2', playable: true },
  { number: 31, description: 'Mission 31', playable: false },
  { number: 32, description: 'Mission 32', playable: false },
  { number: 33, description: 'Mission 33', playable: false },
  { number: 34, description: 'Mission 34', playable: false },
  { number: 35, description: 'Mission 35', playable: false },
  { number: 36, description: 'Mission 36', playable: false },
  { number: 37, description: 'Mission 37', playable: false },
  { number: 38, description: 'Eight Tasks, Disruption 3', playable: true },
  { number: 39, description: 'Eight Tasks, three arrows, dead zone', playable: true },
  { number: 40, description: 'Mission 40', playable: false },
  { number: 41, description: 'Mission 41', playable: false },
  { number: 42, description: 'Nine Tasks', playable: true },
  { number: 43, description: 'Mission 43', playable: false },
  { number: 44, description: 'Mission 44', playable: false },
  { number: 45, description: 'Mission 45', playable: false },
  { number: 46, description: 'Mission 46', playable: false },
  { number: 47, description: 'Ten Tasks', playable: true },
  { number: 48, description: 'Mission 48', playable: false },
  { number: 49, description: 'Mission 49', playable: false },
  { number: 50, description: 'Mission 50', playable: false },
];
